version: 1.0.{build}

configuration: CI
platform: Any CPU

before_build: 
- ps: >-
    $vsixFilePathToUpdate = Resolve-Path "*\source.extension.vsixmanifest"

    [xml]$vsixXml = (Get-Content $vsixFilePathToUpdate)

    $ns = New-Object System.Xml.XmlNamespaceManager $vsixXml.NameTable

    $ns.AddNamespace("ns", $vsixXml.DocumentElement.NamespaceURI)

    $version = $vsixXml.SelectSingleNode("//ns:Identity", $ns) | select Version
    
    $version.Value += $env:APPVEYOR_BUILD_NUMBER

    $vsixXml.Save($vsixFilePathToUpdate);

build:
  verbosity: minimal

artifacts:
- path: '**/*.vsix'
  name: Nightly Build